export const argGameAbi = [
  { type: "constructor", inputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "RESCUE_DELAY_BLOCKS", inputs: [], outputs: [{ name: "", type: "uint256", internalType: "uint256" }], stateMutability: "view" },
  { type: "function", name: "acceptOwnership",  inputs: [], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "claimPrize",       inputs: [], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "endSeason",        inputs: [{ name: "_winner",  type: "address", internalType: "address" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "fundPrizePool",    inputs: [], outputs: [], stateMutability: "payable" },
  {
    type: "function", name: "getSeasonInfo", inputs: [],
    outputs: [
      { name: "name",          type: "string",  internalType: "string"  },
      { name: "number",        type: "uint256", internalType: "uint256" },
      { name: "active",        type: "bool",    internalType: "bool"    },
      { name: "prize",         type: "uint256", internalType: "uint256" },
      { name: "currentWinner", type: "address", internalType: "address" },
    ],
    stateMutability: "view",
  },
  { type: "function", name: "isActive",         inputs: [], outputs: [{ name: "", type: "bool",    internalType: "bool"    }], stateMutability: "view" },
  { type: "function", name: "owner",            inputs: [], outputs: [{ name: "", type: "address", internalType: "address" }], stateMutability: "view" },
  { type: "function", name: "pendingOwner",     inputs: [], outputs: [{ name: "", type: "address", internalType: "address" }], stateMutability: "view" },
  { type: "function", name: "pendingWithdrawals", inputs: [{ name: "", type: "address", internalType: "address" }], outputs: [{ name: "", type: "uint256", internalType: "uint256" }], stateMutability: "view" },
  { type: "function", name: "playerRegistry",  inputs: [], outputs: [{ name: "", type: "address", internalType: "address" }], stateMutability: "view" },
  { type: "function", name: "prizePool",        inputs: [], outputs: [{ name: "", type: "uint256", internalType: "uint256" }], stateMutability: "view" },
  // HIGH-07: orphan-prize recovery — owner-only, gated by RESCUE_DELAY_BLOCKS after endSeason
  { type: "function", name: "rescuePrize",      inputs: [{ name: "newRecipient", type: "address", internalType: "address" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "seasonEndedAtBlock", inputs: [], outputs: [{ name: "", type: "uint256", internalType: "uint256" }], stateMutability: "view" },
  { type: "function", name: "seasonName",       inputs: [], outputs: [{ name: "", type: "string",  internalType: "string"  }], stateMutability: "view" },
  { type: "function", name: "seasonNumber",     inputs: [], outputs: [{ name: "", type: "uint256", internalType: "uint256" }], stateMutability: "view" },
  { type: "function", name: "setPlayerRegistry", inputs: [{ name: "registry", type: "address", internalType: "address" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "startSeason",      inputs: [{ name: "name",     type: "string",  internalType: "string"  }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "transferOwnership", inputs: [{ name: "newOwner", type: "address", internalType: "address" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "winner",           inputs: [], outputs: [{ name: "", type: "address", internalType: "address" }], stateMutability: "view" },
  { type: "receive",  stateMutability: "payable" },
  { type: "event", name: "OwnershipTransferStarted", inputs: [{ name: "currentOwner", type: "address", indexed: true,  internalType: "address" }, { name: "pendingOwner", type: "address", indexed: true,  internalType: "address" }], anonymous: false },
  { type: "event", name: "OwnershipTransferred",     inputs: [{ name: "previousOwner",type: "address", indexed: true,  internalType: "address" }, { name: "newOwner",     type: "address", indexed: true,  internalType: "address" }], anonymous: false },
  { type: "event", name: "PrizeClaimed",             inputs: [{ name: "claimant",     type: "address", indexed: true,  internalType: "address" }, { name: "amount",       type: "uint256", indexed: false, internalType: "uint256" }], anonymous: false },
  { type: "event", name: "PrizeFunded",              inputs: [{ name: "funder",       type: "address", indexed: true,  internalType: "address" }, { name: "amount",       type: "uint256", indexed: false, internalType: "uint256" }, { name: "newTotal", type: "uint256", indexed: false, internalType: "uint256" }], anonymous: false },
  // HIGH-07: emitted when owner reroutes an unclaimed prize after the rescue delay
  { type: "event", name: "PrizeRescued",             inputs: [{ name: "recipient",      type: "address", indexed: true,  internalType: "address" }, { name: "originalWinner", type: "address", indexed: true,  internalType: "address" }, { name: "amount",         type: "uint256", indexed: false, internalType: "uint256" }], anonymous: false },
  // HIGH-09: emitted when registry.resetForNewSeason reverts during startSeason
  { type: "event", name: "RegistryResetFailed",      inputs: [{ name: "reason",         type: "bytes",   indexed: false, internalType: "bytes"   }], anonymous: false },
  { type: "event", name: "PlayerRegistrySet",        inputs: [{ name: "registry",     type: "address", indexed: true,  internalType: "address" }], anonymous: false },
  { type: "event", name: "SeasonEnded",              inputs: [{ name: "seasonNumber", type: "uint256", indexed: true,  internalType: "uint256" }, { name: "winner", type: "address", indexed: true, internalType: "address" }, { name: "prize", type: "uint256", indexed: false, internalType: "uint256" }], anonymous: false },
  { type: "event", name: "SeasonStarted",            inputs: [{ name: "seasonNumber", type: "uint256", indexed: true,  internalType: "uint256" }, { name: "name",   type: "string",  indexed: false, internalType: "string"  }], anonymous: false },
  { type: "error", name: "NoActiveSession"    },
  { type: "error", name: "NoPlayersYet"       },
  { type: "error", name: "NoPrizePool"        },
  { type: "error", name: "NoSeasonEndedYet"   },
  { type: "error", name: "NothingToClaim"     },
  { type: "error", name: "NotOwner"           },
  { type: "error", name: "NotPendingOwner"    },
  { type: "error", name: "RegistryNotSet"     },
  { type: "error", name: "RescueTooEarly"     },
  { type: "error", name: "SeasonAlreadyActive"},
  { type: "error", name: "TransferFailed"     },
  { type: "error", name: "WinnerNotLeader"    },
  { type: "error", name: "ZeroAddress"        },
] as const
